bank:
  withdraw:
    successful: "§eTu as récupéré §6§l%amount%§e diamants"
    failed: "§cUne erreur est survenue lors de la récupération à la banque"
    not_enough: "§eTu n'as pas §6§l%amount%§e diamants dans ta banque"
  deposit:
    successful: "§eTu as déposé §6§l%amount%§e diamants à la banque"
    failed: "§cUne erreur est survenue lors du dépôt à la banque"
    not_enough: "§eTu n'as pas §6§l%amount%§e diamants dans ton inventaire"
  balance: "§eTu as §6§l%amount%§e diamants dans ta banque"

messages:
  no_permission: "§cTu n'as pas la permission d'éxecuter cette commande!"

database:
  host: "localhost"
  user: "survival-plus"
  password: "surv+sqlDb1984*"
  database: "survival_plus"
  port: 3306

skills:
  gained: "§6§l%amount% / %amount_for_level%§e §e| §6§n%skill%"
  passed_level: "§eTu es passé niveau §6§l%level%§e en §6§n%skill%"
  not_enough_tokens: "§eTu n'as pas assé de §6§njetons"
  upgrade_bought: "§eTu as acheté §6§l%upgrade%§e pour §6§n%cost%§e jeton(s)"
  upgrade_already_bought: "§eTu as déjà §6§l%upgrade%"
  upgrade_maxed: "§eTon amélioration §6§l%upgrade%§e est déjà maxée"
  upgrade_disabled: "§eTu as §ndésactivé§6§l %upgrade%"
  upgrade_enabled: "§eTu as §nactivé§6§l %upgrade%"
  upgrade_not_possessed: "§eTu n'as pas cette amélioration"

menus:
  back_item: SPECTRAL_ARROW
  close_item: BARRIER
  background_item: GRAY_STAINED_GLASS_PANE
# -2023974026108394531